### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by esuvorov** [arturbosch/sonar-kotlin#41] opened 2017-12-05 13:32 UTC
Hi. I'm trying to use SonarQube on TeamCity. 
It's running in Docker containers. 
I haven't the same problem on my local machine. 
But crash doesn't look like an environment issue. 

```
ERROR: Error during SonarQube Scanner execution
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.codeStyle.CodeEditUtil.saveWhitespacesInfo(CodeEditUtil.java:138)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.saveIndentationToCopy(ChangeUtil.java:129)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyLeafWithText(ChangeUtil.java:107)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LeafElement.replaceWithText(LeafElement.java:154)
	at io.gitlab.arturbosch.detekt.formatting.TrailingSpaces$replaceTracingSpaces$2.invoke(TrailingSpaces.kt:39)
	at io.gitlab.arturbosch.detekt.formatting.TrailingSpaces$replaceTracingSpaces$2.invoke(TrailingSpaces.kt:18)
	at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.withAutoCorrect(ConfigAware.kt:25)
	at io.gitlab.arturbosch.detekt.api.Rule.withAutoCorrect(Rule.kt:17)
	at io.gitlab.arturbosch.detekt.formatting.TrailingSpaces.replaceTracingSpaces(TrailingSpaces.kt:38)
	at io.gitlab.arturbosch.detekt.formatting.TrailingSpaces.visitSpaces(TrailingSpaces.kt:28)
	at io.gitlab.arturbosch.detekt.api.TokenRule.procedure(TokenRule.kt:29)
	at io.gitlab.arturbosch.detekt.api.TokenRule$visit$1.invoke(TokenRule.kt:21)
	at io.gitlab.arturbosch.detekt.api.TokenRule$visit$1.invoke(TokenRule.kt:18)
	at io.gitlab.arturbosch.detekt.api.JunkKt.visitTokens(Junk.kt:20)
	at io.gitlab.arturbosch.detekt.api.JunkKt.visitTokens(Junk.kt:21)
	at io.gitlab.arturbosch.detekt.api.JunkKt.visitTokens(Junk.kt:21)
	at io.gitlab.arturbosch.detekt.api.TokenRule.visit(TokenRule.kt:21)
	at io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:16)
	at io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:23)
	at io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:51)
	at io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
	at io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
	at io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
	at io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:20)
	at io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:24)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
... 3 more
```

**Comment by arturbosch** [comment] 2017-12-05 13:48
Yep, the psi sometimes returns stupid values from nodes and I don't know why. This will be gone in the next release as formatting module was removed in detekt. I will try to find time soon.

**Comment by arturbosch** [comment] 2017-12-15 16:35
This should be fixed in master due to detekt version update. Fell free to reopen if you still have issues.

**Closed by arturbosch** 2017-12-15 16:35 UTC
Labels: blocked

**Comment by esuvorov** [comment] 2017-12-19 08:03
Now I get a new exception: 
```
[10:53:18]ERROR: Error during SonarQube Scanner execution
[10:53:18]java.lang.IllegalStateException: Unable to blame file account-storage/src/main/AndroidManifest.xml
[10:53:18]	at org.sonarsource.scm.git.JGitBlameCommand.blame(JGitBlameCommand.java:128)
[10:53:18]	at org.sonarsource.scm.git.JGitBlameCommand.access$000(JGitBlameCommand.java:44)
[10:53:18]	at org.sonarsource.scm.git.JGitBlameCommand$1.call(JGitBlameCommand.java:112)
[10:53:18]	at org.sonarsource.scm.git.JGitBlameCommand$1.call(JGitBlameCommand.java:109)
[10:53:18]	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:53:18]	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:53:18]	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:53:18]	at java.lang.Thread.run(Thread.java:745)
[10:53:18]Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 8d9b275145d599982597273fd10325b106b43a55
[10:53:18]	at org.eclipse.jgit.api.BlameCommand.call(BlameCommand.java:232)
[10:53:18]	at org.sonarsource.scm.git.JGitBlameCommand.blame(JGitBlameCommand.java:126)
[10:53:18]	... 7 more
[10:53:18]Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 8d9b275145d599982597273fd10325b106b43a55
[10:53:18]	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
[10:53:18]	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:226)
[10:53:18]	at org.eclipse.jgit.blame.BlameGenerator.push(BlameGenerator.java:317)
[10:53:18]	at org.eclipse.jgit.api.BlameCommand.call(BlameCommand.java:216)
[10:53:18]	... 8 more
[10:53:18]ERROR:
```
Didn't try run it on my local machine. Right on the CI. 
Now will try to run it locally.

**Comment by esuvorov** [comment] 2017-12-19 14:25
It works on some dedicated folders. But if I run on the whole project it doesn't.
I'll try to split the project into small parts and see what we get..

**Comment by arturbosch** [comment] 2017-12-19 20:29
Are you sure it is caused by the sonar-kotlin plugin? The stacktrace tell me that it is a problem of the git plugin. 
`MissingObjectException: Missing unknown 8d9b275145d599982597273fd10325b106b43a55` and `IllegalStateException: Unable to blame file account-storage/src/main/AndroidManifest.xml`
It does not even mention one of sonar-kotlin files in the stacktrace ... :/
