### ISSUE TITLE
java.lang.NullPointerException: Call ofType() first

### ISSUE THREAD

**Issue by sandaliqbal** [arturbosch/sonar-kotlin#47] opened 2017-12-15 04:45 UTC
I'm using this plugin and during sonar scanner execution I get this error:

ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException: Call ofType() first
	at org.sonar.api.internal.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.sonar.api.batch.sensor.coverage.internal.DefaultCoverage.doSave(DefaultCoverage.java:142)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:43)
	at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJacocoReportAnalyzer.readExecutionData(KotlinJacocoReportAnalyzer.kt:123)
	at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJacocoReportAnalyzer.analyse(KotlinJacocoReportAnalyzer.kt:84)
	at io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor.execute(KotlinJaCoCoSensor.kt:68)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)

**Comment by arturbosch** [comment] 2017-12-15 16:36
Duplicate of #40. Should be fixed by https://github.com/arturbosch/sonar-kotlin/commit/f0a9abeaffbf84b1e1d721c6983060f07548dce9

**Closed by arturbosch** 2017-12-15 16:36 UTC
