### ISSUE TITLE
Coverage is OK, but junit tests report missing

### ISSUE THREAD

**Issue by MichalMichalak** [arturbosch/sonar-kotlin#66] opened 2018-04-27 23:53 UTC
Hello. I've managed to get my project analyzed and I can see Detekt and Jacoco reports in Sonar. Unfortunately the JUnit report is missing. Is that an expected behavior? If not, how do I configure my project to get JUnit repot? Thanks.

**Comment by arturbosch** [comment] 2018-04-28 06:26
Duplicate of #65. The feature is requested :)

**Closed by arturbosch** 2018-04-28 06:26 UTC
Labels: duplicate
